### ISSUE TITLE
Properly organize the project

### ISSUE THREAD

**Issue by R-Yash** [ashok-arora/spotify-hit-predictor#1]
- **Currently all the files for the project are in the main directory.**
- **I want to organize all these files in different directories to make the project less cluttered**

**Comment by ashok-arora** [comment]
Sure! ✨
What would be a good folder structure?

**Comment by R-Yash** [comment]
Organize all the datasets in a specific folder labeled datasets, all the python files and Jupyter notebook in a folder called model and the docker and hiroku related files in a folder called server.
